# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 487702aec8d00c6619676e09387e8e94baf0fa10c059cc049598bf75f039ded696065a34027f37440a15e86a4ed331e61e68b14ecf1a1b2f6cbc5ca34bbb6506

test:
  secret_key_base: 6cdf2c0962f9a5fe74cac0faef4ab274fabeeb4b723ae258c4573631fdb974fd4487ce7473d46e773915e1e5b0822d0ee16ff1af20acc649729cb28127a7d88d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
